#! perl

################################################################################

sub on_init {
    my ($self) = @_;
    my $hotkey = $self->x_resource("previous-command-output") || "M-1";
    $self->parse_keysym($hotkey, "perl:previous-command-output:paste")
        or warn "unable to register '$hotkey' as previous-command-output paste hotkey\n";
    ()
}

sub on_user_command {
    my ($self, $cmd) = @_;
    $cmd eq "previous-command-output:paste" and $self->paste;
    ()
}

sub paste {
    my ($self) = @_;
    my ($lnum, $cnum) = $self->screen_cur();

    my $string = $self->ROW_t($lnum-1);
    $string =~ s/^\s+//g;
    $string =~ s/\s+$//g;
    $string =~ s/\x{ffff}//g;

    my $output = $self->locale_encode($string);

    $self->tt_write ($output);
}

# vim:sw=4:ts=4
