#! perl

sub on_start {
    my ($self) = @_;
    $self->grab_button (3, urxvt::ControlMask);
    ()
}

sub on_button_press {
    my ($self, $event) = @_;

    if ($event->{button} == 3) {
        my $popup = $self->popup ($event)
            or return 1;

        my $word = $self->selection;

        my $title = $word;
        $title =~ s/[\x00-\x1f\x80-\x9f]/·/g;
        $title =~ s/\W//g; # 删除所有非英文字母

#       my @dict = `/usr/bin/locale`;                          # 只有第一次的执行结果正确，后来 locale 被自动修改成 POSIX
#       my @dict = `export LANG=zh_CN.UTF-8; /usr/bin/cal`;    # 除非每次显示重申 locale
        my @dict = `export LANG=zh_CN.UTF-8; /usr/bin/sdcv -n --utf8-output -u 'XDICT英汉辞典' "$title"`
            or return 2;

        splice(@dict, 0, 4); # 删除前四行
        splice(@dict, -1);   # 删除末尾行
        splice(@dict, 10);   # 只保留十行
        for my $eachline (@dict) {
            chomp $eachline;
            $eachline = $self->locale_decode($eachline);
            $popup->add_title ($eachline);
        }

        $popup->show;

# XXX 用 overlay 作 todo list 效果还是不错的
# overlay_simple 有可恶的边框
# overlay 识别不了 \n 换行符
#       my $width = 0;
#       my $height = 0;
#       my $text = "";
#       for my $eachline (@dict) {
#           chomp $eachline;
#           $eachline = $self->locale_decode($eachline);
#           #$text = sprintf ("%s\n%s", $text, $eachline);
#           $text = sprintf ("%s\n%s", "123", "aaa");
#           my $length = $self->strwidth ($eachline);
#           $height = $height + 1;
#           $width  = $length if ($width < $length);
#       }
#       $self->{overlay} = $self->overlay (-1, 0, $width, $height, urxvt::OVERLAY_RSTYLE, 0);
#       $self->{overlay}->set (0, 0, $text);

        return 1;
    }

    ()
}

