#! perl

my $DEBUG = 1;
my $DEBUG_FILE = '/tmp/urxvt_dict.log';
my $DEBUG_FH;
our $DICT = '/sun/.urxvt/dict.sh';
our $PROC;

sub on_start {
    my ($self) = @_;
    $self->grab_button (3, urxvt::AnyModifier);

    if ($DEBUG){
        open($DEBUG_FH, ">$DEBUG_FILE");
        select((select($DEBUG_FH), $| = 1)[0]);
    }

    ()
}


sub leave {
    my ($self, $event) = @_;

    if ($DEBUG) {
        close($DEBUG_FH);
    }

    if ($PROC) {
        close ($PROC)
    }
}

sub on_button_press {
    my ($self, $event) = @_;

    if ($event->{button} == 3) {
        print $DEBUG_FH "1======\n";
        my $popup = $self->popup ($event)
            or return 1;

        print $DEBUG_FH "2======\n";
        my $title = $self->selection;
        utf8::encode($title);
        # XXX 9.11 - don't swap perl env with real env, save and restore it ....
        # http://cvs.schmorp.de/rxvt-unicode/Changes
        # 只有 9.11 之后的版本可以直接执行 sdcv 命令，否则要提前执行 export LANG=zh_CN.UTF-8;
        if (open($PROC, "export SDCV_HISTSIZE=512; /usr/bin/sdcv -n --utf8-output -u 'jmdict-ja-en' -u 'xdict-en-zh' '$title' 2>&1 |")) {
            $title = join('', <$PROC>);
        } else {
            print $DEBUG_FH "?======\n";
        }
        print $DEBUG_FH "3======\"$title\"\n";
        my @dict = ($title =~ /.*\n/g);
        splice(@dict, 0, 4); # 删除前四行
        splice(@dict, -1);   # 删除末尾行
        splice(@dict, 10);   # 只保留十行
        for my $eachline (@dict) {
            print $DEBUG_FH "3.0======\"$eachline\"\n";
            chomp $eachline;
            print $DEBUG_FH "3.1======\"$eachline\"\n";
            $eachline = $self->locale_decode($eachline);
            print $DEBUG_FH "3.2======\n";
            $popup->add_title ($eachline);
            print $DEBUG_FH "3.3======\n";
        }
        print $DEBUG_FH "4======\n";

        $popup->show;
        print $DEBUG_FH "5======\n";

        return 0;
    }

    ()
}

# XXX 用 overlay 作 todo list 效果还是不错的 {{{1
# overlay_simple 有可恶的边框
# overlay 识别不了 \n 换行符
#       my $width = 0;
#       my $height = 0;
#       my $text = "";
#       for my $eachline (@dict) {
#           chomp $eachline;
#           $eachline = $self->locale_decode($eachline);
#           #$text = sprintf ("%s\n%s", $text, $eachline);
#           $text = sprintf ("%s\n%s", "123", "aaa");
#           my $length = $self->strwidth ($eachline);
#           $height = $height + 1;
#           $width  = $length if ($width < $length);
#       }
#       $self->{overlay} = $self->overlay (-1, 0, $width, $height, urxvt::OVERLAY_RSTYLE, 0);
#       $self->{overlay}->set (0, 0, $text);

