#!/usr/bin/env bash
# 2009 Paul Mansfield <paul.mansfield@mansteck.co.uk>
# License:    GPL, http://www.gnu.org/copyleft/gpl.html

if [ $1 != "useage" ]; then
    action=$1;shift
fi

useage() {
    echo "  $(basename $0)"
    echo "    List notes"
    echo ""
}

case $1 in
    "useage")
        useage
    ;;

    "-h")
        useage
    ;;

    *)
        cat "$TODO_FILE" "$DONE_FILE" | grep -o '\bnote\:\w*' | sort -u
    ;;
esac
