#!/bin/sh

# XXX ##############################################
# sudo ln -sf ~/.Xlogout /etc/X11/Xreset.d/Xlogout
# ############################################## XXX

pkill autossh
pkill inotifywait
pkill sshfs
pkill remind
