#!/bin/sh
# % apt-get install xserver-xorg xdm iceweasel sudo vim zsh git awesome awesome-extra
# % apt-get install ttf-wqy-microhei ttf-wqy-zenhei ttf-dejavu ruby1.8 rubygems1.8
# % apt-get install autossh xscreensaver autocutsel moc synergy remind inotify-tools
# % apt-get install mutt msmtp fetchmail procmail weechat bitlbee python-simplejson
# % apt-get install devscripts dupload ctags cscope ack-grep feh xcompmgr rxvt-unicode
# % apt-get install sdcv xsel xdg-user-dirs
#
# FF: AutoPager, AutoProxy, Delicious, Download Statusbar, FlagFox, Organize Status Bar, Tab Utilities, TinyURL, Vimperator, rein


# ssh 翻墙隧道 0:PORT 的写法使得局域网(虚拟机)可以共享此隧道
/usr/bin/autossh -f -N -D 0:9527 du1abadd.org

# 强制启用 Ctrl-Alt-Backspace(重启图形界面) 组合键
/usr/bin/setxkbmap -option terminate:ctrl_alt_bksp

# 关闭机箱喇叭蜂鸣 设定键鼠灵敏度
/usr/bin/xset b off m 3 10 r rate 400 30

# 加载自定义的特殊的键盘功能键
/usr/bin/xmodmap ~/.Xmodmaprc

# 设置屏保
/usr/bin/xscreensaver -no-splash &

# 统一剪贴板
/usr/bin/autocutsel -s PRIMARY -f

# 启动应用程序
/usr/bin/x-www-browser & #浏览器
/usr/bin/fetchmail -d 600 #邮件
/usr/bin/mocp -S #音乐服务
/usr/local/bin/lrcdis & # 歌词
#/usr/bin/gdlinux # Google Desktop
#/usr/local/bin/eclimd & # eclimd

# 一套键鼠控制多台机器，服务器端
/usr/bin/synergys # synergy server
# 客户端，由服务器端的键鼠控制
# sh -c "echo '/usr/bin/synergyc -d ERROR --restart 192.168.1.60' >> /etc/X11/xdm/Xsetup"

# pull, monitor, push TODO 如果同步失败，邮件通知自己
/usr/bin/rsync -azu du1abadd.org:~/.task/ ~/.task/ &
/usr/bin/remind -z -k'~/.task/notify-wm %s &' ~/.task/reminders &
/usr/bin/inotifywait -mrq -e modify,delete,create,attrib ~/.task/ | \
    while read file; do
        rsync -azu ~/.task/ du1abadd.org:~/.task/ &
    done &

# 使用渐隐、阴影特效
/usr/bin/xcompmgr -f &

# 输入法
/usr/bin/fcitx

# 启动窗口管理器
/usr/bin/awesome
