#!/bin/zsh

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    DUE"
  echo "      run me from a cron job"
  echo "        once a day."
  echo ""
  exit
}

export DOTREMINDERS="/sun/.todo/var/remind/index.rem"
reminds=(${(s.
.)"$(rem -s+4 | /bin/grep $(date +"%Y/%m/%d" -d "tomorrow") \
    | sed -e 's?..../\(../..\).*\(.\+:.*\)[ap]m \(.*\)?\3 due:\1 \2?g')"})
for task in $reminds; do
    if ! grep $task $TODO_FILE > /dev/null 2>&1; then
        $TODO_SH command add $task
    fi
done

tod=$(date +"due:%m/%d")
tasks=(${(s.
.)"$($TODO_SH list "$tod" | awk '/^[0-9]+/ { print $1 }')"})
for id in $tasks; do
    # (D) meaning to(d)ay
    $TODO_SH command pri "$id" d
done

tom=$(date +"due:%m/%d" -d "+1 day")
tasks=(${(s.
.)"$($TODO_SH list "$tom" | awk '/^[0-9]+/ { print $1 }')"})
for id in $tasks; do
    # (T) meaning (t)omorrow
    $TODO_SH command pri "$id" t
done

# vim: ft=zsh
