#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    Add and prioritize A:"
  echo "      $(basename $0) ITEM"
  echo "        Add an item and prioritize it A in one step"
  echo ""
  exit
}

if "$TODO_SH" command add "$@"; then
    # figure out the line of what we just added, and prioritize it A
    line=`sed -n '$ =' "$TODO_FILE"`
    echo "$line"
    "$TODO_SH" command pri "$line" A 
fi
