customization:
  rime_version: 1.5.3+sbxlmdsl+git~384f9b3
patch:
  schema_list:
    - schema: sbfm
  key_binder:
    bindings:
      - {accept: 9, send: Page_Up, when: has_menu}
      - {accept: 0, send: Page_Down, when: has_menu}
      - {accept: 9, send: Page_Up, when: paging}
      - {accept: 0, send: Page_Down, when: paging}
      - {accept: "Control+Alt+j", toggle: full_shape, when: always}
      - {accept: "Control+Alt+f", toggle: traditional, when: always}
      - {accept: "Control+period", toggle: ascii_punct, when: always}
  switcher:
    hotkeys:
      - "Control+Alt+k"
  ascii_composer/switch_key:
    Shift_L: noop
    Shift_R: inline_ascii

