distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.0.4
install_time: "Mon Mar 14 23:31:52 2022"
installation_id: "2eee5061-5711-4984-a2e5-8369b552cc1d"
rime_version: 1.5.3