distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Sat Feb 16 10:10:54 2019"
installation_id: "550072e9-b8b4-469b-b1a0-a0b504cbce69"
rime_version: 1.4.0