# Rime schema settings
# encoding: utf-8

schema:
  schema_id: sbfm
  name: "声笔飞码"
  version: "9.5"
  author:
    - 戴石麟 <https://sbxlm.gitee.io>
  dependencies:
    - sbzdy
    - sf
    - sbf
    - spf

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: ascii_punct
    states: [ 。，, ．， ]
  - name: full_shape
    reset: 0
  - name: pro_char
    reset: 0
    states: [ 词组, 单字 ]
  - name: is_enhanced
    reset: 1
    states: [ 常规, 增强 ]
  - name: zh_trad
    reset: 0
    states: [ 简体, 繁體 ]
  - name: auto_inline
    reset: 1

engine:
  processors:
    - selector
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@sbzdy
    - affix_segmentor@fmsbb_lookup
    - affix_segmentor@bihua_lookup
    - affix_segmentor@pinyin_lookup
    - affix_segmentor@sbbb_lookup
    - affix_segmentor@zhlf_lookup
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator
    - table_translator@sf     #支持sf标点简词
#   - table_translator@sbf    #支持sbf标点简词
#   - table_translator@spf    #支持spf标点简词
    - table_translator@sbzdy   #支持自定义词典
    - table_translator@sb
    - table_translator@fmsbb
    - table_translator@spbgd
    - table_translator@spbb
    - lua_translator@date_translator
    - lua_translator@time_translator
    - lua_translator@number_translator
    - table_translator@sbbb_lookup
    - table_translator@sbs$
    - table_translator@sbs$b
    - table_translator@sps$
    - table_translator@sps$b
    - table_translator@fmsbb_lookup
    - table_translator@bihua_lookup
    - script_translator@pinyin_lookup
    - script_translator@zhlf_lookup
  filters:
    - reverse_lookup_filter@fmsbb_reverse_lookup
    - reverse_lookup_filter@bihua_reverse_lookup
    - reverse_lookup_filter@pinyin_reverse_lookup
    - reverse_lookup_filter@sbbb_reverse_lookup
    - reverse_lookup_filter@zhlf_reverse_lookup
    - simplifier@prompt
    - simplifier
    - uniquifier

speller:
  alphabet: "qwertasdfgzxcvbyuiophjklnmAEUIOQWRTSDFGZXCVBYPHJKLNMAEUIO,;/.'"
  initials: "qwrtsdfgzxcvbyphjklnm"
  auto_select: true
  auto_clear: max_length
  max_code_length: 6
  
translator:
  dictionary: sbfm
  enable_user_dict: true
  enable_encoder: true
  enable_sentence: false
  strict_spelling: true
  enable_completion: false
  encode_commit_history: true
  forced_selection: false    # 是否采用强制选重
  single_selection: false   # 默认为false，表示采用两次选重而不是单次选重
  stop_change: false         # 默认为false，要进行调频和自动造词
  delete_threshold: 10000     # 废词删除阈值，默认为10000
  max_phrase_length: 5       # 自动造词长度限制，默认为5，建议不超过10
  initial_quality: 1000

sbzdy:
  tag: sbzdy
  dictionary: sbzdy
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  strict_spelling: true
  enable_completion: true
  encode_commit_history: false
  prefix: "u"
  tips: "〔自定义〕"

simplifier:
  opencc_config: s2t.json
  option_name: zh_trad

sb:
  dictionary: sb
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 1

sf:
  dictionary: sf
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 10
 
sbf:
  dictionary: sbf
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 2
 
spf:
  dictionary: spf
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 2

fmsbb:
  dictionary: fmsbb
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 0

spbgd:
  dictionary: spbgd
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 1

spbb:
  dictionary: spbb
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 1
   
bihua_lookup:
  tag: bihua_lookup
  dictionary: bihua
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  strict_spelling: true
  enable_completion: true
  encode_commit_history: false
  tips: "〔笔画反查〕"

bihua_reverse_lookup:
  tags: [ bihua_lookup ] 
  overwrite_comment: true
  dictionary: sbfmfc
    
sbs$:
  dictionary: sbs$
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 0
  comment_format:
    - xform|\$||
    - xform|~||
  
sbs$b:
  dictionary: sbs$b
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: -4
  comment_format:
    - xform|\$||
    - xform|~||

sps$:
  dictionary: sps$
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: 0
  comment_format:
    - xform|\$||
    - xform|~||
    
sps$b:
  dictionary: sps$b
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: true
  strict_spelling: true  
  initial_quality: -4
  comment_format:
    - xform|\$||
    - xform|~||

pinyin_lookup:
  tag: pinyin_lookup
  dictionary: sbpy
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  strict_spelling: true
  enable_completion: true
  encode_commit_history: false
  prefix: "a"
  tips: "〔拼音反查〕"

pinyin_reverse_lookup:
  tags: [ pinyin_lookup ] 
  overwrite_comment: true
  dictionary: sbfmfc
  
fmsbb_lookup:
  dictionary: fmsbb_lookup
  tag: fmsbb_lookup
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: false
  strict_spelling: true  
  initial_quality: -2

fmsbb_reverse_lookup:
  tags: [ fmsbb_lookup ] 
  overwrite_comment: true
  dictionary: fmsbb
  
sbbb_lookup:
  dictionary: sbbb
  tag: sbbb_lookup
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  enable_completion: false
  strict_spelling: true  
  initial_quality: -2

sbbb_reverse_lookup:
  tags: [ sbbb_lookup ] 
  overwrite_comment: true
  dictionary: sbfmfc

zhlf_lookup:
  tag: zhlf_lookup
  dictionary: zhlf
  enable_user_dict: false
  enable_encoder: false
  enable_sentence: false
  strict_spelling: true
  enable_completion: true
  encode_commit_history: false
  prefix: "i"
  tips: "〔两分反查〕"

zhlf_reverse_lookup:
  tags: [ zhlf_lookup ] 
  overwrite_comment: true
  dictionary: sbfmfc

punctuator:
  import_preset: symbols

recognizer:
  patterns:
    sbzdy: "^u[qwrtsdfgzxcvbyphjklnm][a-z0-9]*$"
    bihua_lookup: "^[aeiou][aeiou]*'?$"
    pinyin_lookup: "^a[qwrtsdfgzxcvbyphjklnm][a-z]*'?$"
    sbbb_lookup: "^[qwrtsdfgzxcvbyphjklnm][aeuio]{3}$"
    zhlf_lookup: "^i[qwrtsdfgzxcvbyphjklnm][a-z]*'?$"
    fmsbb_lookup: "^[qwrtsdfgzxcvbyphjklnm]{2}[aeuio]{2}$"
    retention: "^[qwrtsdfgzxcvbyphjklnm][aeuio][aeuio]|o[qwrtsdfgzxcvbyphjklnm0-9][a-z0-9]*$"
    punct: '^\\([0-9]|10|[A-Za-z]+)$'

key_binder:
  import_preset: default
  bindings:
    - { when: has_menu, accept: Shift+Tab, send_sequence: "{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}{Page_Down}" }
    - { when: paging, accept: Shift+Tab, send: Page_Up }
    - { when: has_more, accept: Tab, send: Page_Down }
    - { when: last_punct, accept: Return, send_sequence: "{Left}{space}{space}" }
    - { when: last_punct, accept: Tab, send_sequence: "{Left}{Left}{space}{space}" }
    - { when: ok_second, accept: Tab, send_sequence: "{Left}{space}{space}" }
    - { when: ok_second, accept: Return, send_sequence: "{Left}{space}{space}" }
    - { when: ok_third, accept: Return, send_sequence: "{Left}{Left}{space}{space}" }
    - { when: ok_third, accept: Tab, send_sequence: "{Left}{space}{space}" }
    - { when: ok_fourth, accept: Return, send_sequence: "{Left}{Left}{space}{space}" }
    
menu:
  page_size: 6
  alternative_select_keys: " aeuio"
  alternative_select_labels: [" ",ａ,ｅ,ｕ,ｉ,ｏ]

