# Rime dict
# encoding: utf-8
#
# sf二字词
#
# 自定义(IT相关)
---
name: sf
version: "9.5"
sort: by_weight
use_preset_vocabulary: false
columns:
  - text
  - code
...
一个	y/
没有	m,
我们	w/
他们	t/
什么	s/
自己	z'
知道	z.
可以	k'
这个	z/
就是	j;
中国	z;
启动	q,
这样	z,
已经	y'
发展	f'
因为	y.
现在	x,
你们	n/
工作	g/
问题	w;
可是	k;
经济	j.
还是	h;
成功	c,
如果	r;
不过	b,
国家	g.
企业	q;
所以	s'
生效	s.
还有	h,
一点	y;
进行	j/
但是	d;
而且	v;
心中	x;
今天	j,
担心	d.
一样	y,
更加	g'
第一	d,
为了	w'
如何	r/
失败	s;
市场	s,
看到	k,
爱人	v/
同时	t;
过去	g,
系统	x'
当然	d/
发现	f,
希望	x.
孩子	h'
认为	r.
人民	r'
先生	x/
不是	b;
必须	b/
那些	n;
无法	w.
忽然	h/
情况	q.
明白	m/
朋友	p,
北京	b.
通过	t,
发生	f/
离开	l,
美国	m;
领导	l'
重启	c.
继续	j'
非常	f;
方法	f.
提高	t.
提出	t'
目前	m.
其他	q/
会议	h.
老人	l/
难道	n.
完成	w,
立刻	l.
能力	n'
看看	k/
才能	c'
历史	l;
然而	r,
那样	n,
此时	c;
儿子	v'
科学	k.
不能	b'
查看	c/
共同	g;
妻子	q'
登录	d'
面对	m'
安排	v,
漂亮	p.
旁边	p'
欧洲	v.
贫困	p;
脾气	p/
