# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = "$time$character"
right_format = "$all$directory[](fg:#4271AE)"

[directory]
style = "fg:#ffffe0 bg:#4271AE"
read_only_style = "red bg:#4271AE"
format = "[ $path]($style)[$read_only]($read_only_style)"

# https://github.com/Fantantonio/Emoji-List-Unicode
[character]
success_symbol = "[💲](bg:#4271AE)"
error_symbol = "[🔥](bg:#4271AE)"
vimcmd_symbol = "[🐧](bg:#4271AE)"
vimcmd_replace_one_symbol = "[🐧](bg:#4271AE)"
vimcmd_replace_symbol = "[🐧](bg:#4271AE)"
vimcmd_visual_symbol = "[🐧](bg:#4271AE)"

# bug in starship-1.25.0
[maven]
disabled = true

[time]
disabled = false
time_format = "%R"
style = "bold fg:#c6c6c7 bg:#4271AE"
format = '[](fg:#4271AE)[$time]($style)'

[git_status]
ignore_submodules = true
conflicted  = '!'
ahead       = '+'
behind      = '-'
diverged    = '#'
up_to_date  = ''
untracked   = '?'
stashed     = '.'
modified    = 'M'
staged      = 'A'
renamed     = 'R'
deleted     = 'D'
