# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = "$character"
right_format = "$all$directory[](fg:#4271AE)"

[directory]
style = "fg:#ffffff bg:#4271AE"
read_only_style = "red bg:#4271AE"
format = "[$read_only]($read_only_style)[ $path]($style)"

# https://github.com/Fantantonio/Emoji-List-Unicode
[character]
success_symbol = "💲"
error_symbol = "❓"
vimcmd_symbol = "🐧"
vimcmd_replace_one_symbol = "🐧"
vimcmd_replace_symbol = "🐧"
vimcmd_visual_symbol = "🐧"

[git_status]
ignore_submodules = true
conflicted  = '!'
ahead       = '+'
behind      = '-'
diverged    = '#'
up_to_date  = ''
untracked   = '?'
stashed     = '.'
modified    = 'M'
staged      = 'A'
renamed     = 'R'
deleted     = 'D'
