#!/bin/sh

# 获取这封邮件的主题
subject=$(formail -zfxSubject \
    | perl -MEncode -MMIME::EncWords -ne 'print decode("UTF8", encode("UTF8", MIME::EncWords::decode_mimewords($_, Charset => "UTF8")))')

# 添加一项
task add "${subject}"

