#!/bin/sh

###############################################################################
# taskopen - file based notes with taskwarrior
#
# Copyright 2010, Johannes Schlatow, Jostein Berntsen.
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the
#
#     Free Software Foundation, Inc.,
#     51 Franklin Street, Fifth Floor,
#     Boston, MA
#     02110-1301
#     USA
#
###############################################################################

task add +email $(grep '^Subject:' $* | cut -d: -f 2-)

# 获取刚刚由 mutt2task 添加的 task id
TASK=$(task rc._forcecolor=no newest | sed -n '3s/^\s\?\([^ ]\+\).*/\1/p')

# 获取这封邮件的 message-id
ANNO=$(egrep -A1 -i '^message-id' $* | paste -s |sed 's/[ \t][ \t]*//g' | sed -e 's/^\(M.*>\)[A-Z].*/\1/g')

# 为最新的 task 添加 message-id
task $TASK ann $ANNO

