#!/bin/bash -

set -f

LABEL="$1"
FNAME="$2"
NFNAME="/tmp/mutt-xlabel-`basename "$2"`.$$"

echo "1: $1" >> /tmp/11
echo "2: $2" >> /tmp/11

# 行首多出一个等号的问题，暂时解决
LABEL=${LABEL//=/}

if [ x"$LABEL" = "x" ]; then
	NEW="X-Label" # delete this field
else
	NEW="X-Label: $LABEL"
fi

formail -I "$NEW" < "$FNAME" > "$NFNAME"

# if we created a new file, step over the old one
if [ -f "$NFNAME" ]; then
	mv "$NFNAME" "$FNAME"
fi

# vi:noet:
