#! /bin/sh

echo ''
if ! hostname | grep "^verns-worktop" > /dev/null 2>&1; then
    echo 'Cheers,\n-- \nVern'
    echo 'vim -c ":s(^(ZnQr8va1puvan.(|:s)\d\(\S\)) \\U\\1)g|:1 normal g??"'
else
    case "$1" in
    en)
        echo 'Cheers,'
        LANG=en_US.UTF-8 && echo "-- \nSun Wuan\n`date +"%Y.%m.%d(%a)"`";;
    ja)
        echo '以上、よろしくお願いいたします。'
        LANG=ja_JP.UTF-8 && echo "-- \n`echo "0x5B6B0x6B660x5B89" | ascii2uni -q`\n`date +"%Y.%m.%d(%a)"`";;
    *)
        LANG=zh_CN.UTF-8 && echo "-- \n`echo "0x5B590x6B660x5B89" | ascii2uni -q`\n`date +"%Y.%m.%d(%a)"`";;
    esac
    echo 'TEL: 7998-8513'
fi

