#!/bin/sh

DESC=${*}
DESC=`echo ${DESC} | sed -e "s/\(^@[^ ]*\) /<span color='#00FF00'>\1<\/span> /g"`                   # context
DESC=`echo ${DESC} | sed -e "s/\(^+[^ ]*\) /<span color='#00FFFF'>\1<\/span> /g"`                   # project
DESC=`echo ${DESC} | sed -e "s/\(^(.)\) /<span color='#FF0000'>\1<\/span> /"`                       # priority
DESC=`echo ${DESC} | sed -e "s/ \(@[^ ]*\)/ <span color='#00FF00'>\1<\/span>/g"`                    # context
DESC=`echo ${DESC} | sed -e "s/ \(+[^ ]*\)/ <span color='#00FFFF'>\1<\/span>/g"`                    # project
DESC=`echo ${DESC} | sed -e "s/\([0-9]\{2\}[-/][0-9]\{2\}\)/<span color='#FF00FF'>\1<\/span>/g"`    # date
DESC=`echo ${DESC} | sed -e "s/\(^.*\)$/<span color='#FFFFFF'>\1<\/span>/g"`                        # normal
/bin/echo -E 'naughty.notify({opacity = 0.9, margin = 0, position = "bottom_right", text = string.format("%s", "'${DESC}'"), timeout=180, hover_timeout=0.5 })' | awesome-client -
