#!/bin/bash
#
# DUAL Screen
#
#       ----
#       { rule = { instance = "CMatrix" },
#       properties = { floating=true, ontop=true },
#	    callback = function (c)
#	        c.screen = 1
#           c:geometry( { x = 0, y = 0, width = 3840, height = 1080 } )
#	    end },
#       ----
#
mode=$1
#file="/tmp/.screensaver.png"
file="/sun/.config/awesome/screenlock.png"

case $mode in
    pause)
        pkill cmatrix
        /usr/bin/x-terminal-emulator +tr -bg lightgray -name CMatrix -T CMatrix -e zsh -c "cmatrix -a -b -x -u 5 -C white"
        ;;
    lock)
        #import -window root $file
        /usr/bin/i3lock -f -i $file && pkill cmatrix
        sleep 600
        pgrep i3lock && xset dpms force off
        ;;
esac
