#!/bin/bash
#
# DUAL Screen
#
#       ----
#       { rule = { instance = "CMatrix" },
#       properties = { floating=true, ontop=true },
#	    callback = function (c)
#	        c.screen = 1
#           c:geometry( { x = 0, y = 0, width = 3840, height = 1080 } )
#	    end },
#       ----
#
# -tabbedalt
#
# tabbedalt 插件激活后，-bg 无法生效。
# 为保持屏保底色为黑色，禁用 tabbedalt
#
mode=$1
#file="/tmp/.screensaver.png"
file="/sun/.config/awesome/screenlock.png"

case $mode in
    pause)
        xset dpms 600
        pkill cmatrix
        /usr/bin/x-terminal-emulator --name="CMatrix" -o background_image="none" -o background="#333333" -T CMatrix -e zsh -c "cmatrix -a -b -u 2 -C black"
        xset dpms 0
        ;;
    lock)
        #import -window root $file
        /usr/bin/i3lock -f -i $file && pkill cmatrix
        sleep 600
        pgrep i3lock && xset dpms force off
        ;;
esac
