[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = [ "m", "S" ]
run  = "plugin what-size -- '--clipboard'"
desc = "Calc size of selection or cwd"

[[mgr.prepend_keymap]]
on = [ "M" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "`" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "m", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = [ "m", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

