[mgr]
ratio = [18, 32, 50]
#sort_by = "btime"
sort_reverse = true
linemode = "size"

[opener]
view_images = [
    {
        run = 'mime=$(file -Lb --mime-type -- %s1) && copyq write "$mime" - < %s1 && copyq select 0 && qiv %s',
        block = true
    }
]

[open]
# 文件打开方式
prepend_rules = [
    { url = "*.{png,jpg,jpeg,gif,bmp}", use = "view_images" },
]
